### PR TITLE
Add support for local songs

### PR DESCRIPTION
**Pull request by pncnmnp**
Based on #13

### CODE REVIEW

**Comment by ology** [comment]
Wow. That was fast. Testing now...

**Comment by pncnmnp** [comment]
@ology Thanks! I am also cleaning it up a bit to make it simpler to manage. We can easily get rid of `local_music_meta` method.

**Comment by ology** [comment]
My tests work perfectly. Woo!

**Comment by pncnmnp** [comment]
It looks much better now. I will do some more testing tomorrow morning, and if all goes well, I will merge this. 
@ology, if you have any further suggestions regarding clarity of code or implementation, do let me know.

**Comment by ology** [comment]
Question: I have tracks downloaded from youtube with bogus characters in the name, like `"/media/gene/New Volume/Audio/Art/David Byrne/The Catherine Wheel/Under the Mountain-U0LotncuPWY.mp3"`. And when the program tries to use it, the DJ says, "'The next song is from your personal collection. None by None." Do you happen to have any idea what's up with that? I am digging into the code to see, but wonder if you know what's going sideways? :-)

**Comment by ology** [comment]
Another question: Can I optionally *not* have a daily question? It seems that this is not configurable and added by `sprinkle_gpt()` - Am I missing something or is that always a thing that will be added?

Also: Get some sleep East-coaster!

**Comment by pncnmnp** [comment]
I've finished testing this. LGTM! I'll merge it tomorrow morning.

**Pull request merged**
